title: I might be an alcoholic
email: jeroenteraa@hotmail.com
description: An engine that creates more stats based on your untappd-data
baseurl: "/beers"

# Build settings
permalink: pretty
encoding: UTF-8

collections:
  monthly:
    output: true
